# -*- coding: utf-8 -*-
"""CatBoostReweighed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gO3TOeVhhfw3Ci4G5kwxSkaT-V2W0REe
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, roc_auc_score
from catboost import CatBoostClassifier
from fairlearn.metrics import (
    MetricFrame,
    selection_rate,
    demographic_parity_difference,
    equalized_odds_difference,
)
from visualization_utils import save_results_visualization, log_summary_row

df = pd.read_csv("../lsac_data.csv")
if "ZFYGPA" in df.columns:
    df = df.rename(columns={"ZFYGPA": "zfygpa"})

needed = ["race", "gender", "lsat", "ugpa", "zfygpa"]

for c in needed:
    df[c] = pd.to_numeric(df[c], errors="coerce")

# Label: above median zfygpa
cutoff_value = np.median(df["zfygpa"])
df["admit_sim"] = (df["zfygpa"] >= cutoff_value).astype(int)

# Features (drop label, zfygpa, protected attrs)
X = df.select_dtypes(include="number").drop(
    columns=["zfygpa", "admit_sim", "race", "gender"], errors="ignore"
)
y = df["admit_sim"].astype(int)
gender = df["gender"].astype(int)
race = df["race"].astype(int)

X_train, X_test, y_train, y_test, g_train, g_test, r_train, r_test = train_test_split(
    X, y, gender, race, stratify=y, test_size=0.25, random_state=42
)

# 2. Reweighting for race (Kamiran & Calders style)
#    We compute weights on TRAINING data only.

r_train_arr = np.array(r_train)
y_train_arr = np.array(y_train)

N = len(y_train_arr)
groups = np.unique(r_train_arr)   # race values
labels = np.unique(y_train_arr)   # 0, 1

# counts
N_g = {g: np.sum(r_train_arr == g) for g in groups}
N_y = {lab: np.sum(y_train_arr == lab) for lab in labels}
N_gy = {
    (g, lab): np.sum((r_train_arr == g) & (y_train_arr == lab))
    for g in groups for lab in labels
}

weights = np.zeros_like(y_train_arr, dtype=float)

for g in groups:
    for lab in labels:
        if N_gy[(g, lab)] == 0:
            continue
        # w(g, y) = (P(g) * P(y)) / P(g, y)
        w_gy = (N_g[g] * N_y[lab]) / (N * N_gy[(g, lab)])
        mask = (r_train_arr == g) & (y_train_arr == lab)
        weights[mask] = w_gy

weights[weights == 0] = 1.0  # safety fallback

catboost = CatBoostClassifier(
    iterations=200,
    depth=5,
    learning_rate=0.05,
    subsample=0.9,
    l2_leaf_reg=1.0,
    loss_function="Logloss",
    random_seed=42,
    verbose=False
)

catboost.fit(X_train, y_train, sample_weight=weights)
proba_baseline = catboost.predict_proba(X_test)[:, 1]
pred_baseline = (proba_baseline >= 0.5).astype(int)

acc_baseline = accuracy_score(y_test, pred_baseline)
auc_baseline = roc_auc_score(y_test, proba_baseline)
print(f"Baseline CatBoost | Accuracy: {acc_baseline:.3f} | AUC: {auc_baseline:.3f}")

def fairness(sens, name):
    mf = MetricFrame(
        metrics={"accuracy": accuracy_score, "selection_rate": selection_rate},
        y_true=y_test,
        y_pred=pred_baseline,
        sensitive_features=sens,
    )

    dp = demographic_parity_difference(y_test, pred_baseline, sensitive_features=sens)
    eo = equalized_odds_difference(y_test, pred_baseline, sensitive_features=sens)

    print(f"\n=== {name.upper()} ===")
    print("Selection rates:\n", mf.by_group["selection_rate"])
    print("Accuracies:\n", mf.by_group["accuracy"])
    print(f"DP difference: {dp:.3f}")
    print(f"EO difference: {eo:.3f}")
    return dp, eo


dp_gender, eo_gender = fairness(g_test, "gender")
dp_race, eo_race = fairness(r_test, "race")

save_results_visualization('catboost_reweighed', y_test, pred_baseline, proba_baseline, sensitive_features_dict={"gender": g_test, "race": r_test})

log_summary_row('catboost_reweighed', acc_baseline, auc_baseline, dp_gender, eo_gender, dp_race, eo_race, '/content/model_results.csv')